apiVersion: v1
kind: Secret
metadata:
  name: store-secret
type: Opaque
data:
  inventory.db.password: cGFzc3dvcmQ=

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: storeapp
data:
  # property-like keys; each key maps to a simple value
  inventory.db.host: mysql
  inventory.db.user: root
  inventory.db: inventory
